--- #YAML:1.0
name:                Test-A8N
version:             0.01
abstract:            Storytest Automation Runner
license:             ~
author:              
    - Michael Nachbaur <mike@nachbaur.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Find:                    0
    Module::Load:                  0
    Moose:                         0
    Pod::Usage:                    0
    Test::Deep:                    0
    Test::FITesque:                0.01
    YAML::Syck:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
