--- #YAML:1.0
name:                Test-A8N
version:             0.03
abstract:            Storytest Automation Runner
license:             perl
author:              
    - Michael Nachbaur <mike@nachbaur.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Find:                    0
    Module::Load:                  0
    Moose:                         0.33
    Pod::Usage:                    0
    Test::Builder:                 0
    Test::Deep:                    0
    Test::FITesque:                0.01
    Test::More:                    0
    WWW::Selenium:                 0
    YAML::Syck:                    0.94
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
